### PR TITLE
fixed import

### PR DESCRIPTION
**Pull request by robtech21**
(don't add .py to the end of module names)

### CODE REVIEW

**Comment by RP400** [comment]
> (don't add .py to the end of module names)

Ive tried without already, and, it doesnt work.

**Comment by robtech21** [comment]
> Ive tried without already, and, it doesnt work.

Then you're not doing it right.

**Comment by RP400** [comment]
> > Ive tried without already, and, it doesnt work.
> 
> Then you're not doing it right.

Can you send a link with the fix ill try

**Comment by robtech21** [comment]
> Can you send a link with the fix ill try

The fix is literally in the PR just merge it with main and try it

**Comment by RP400** [comment]
> > Can you send a link with the fix ill try
> 
> The fix is literally in the PR just merge it with main and try it

Yeah it works (I think) thanks for your help. I credited you in the updates section of my readme

**Review by RP400 — APPROVED** [review]
Thanks alot!

**Review by RP400 — APPROVED** [review]

**Pull request merged**
